### ISSUE TITLE
Serializer from Threeten backport

### ISSUE THREAD

**Issue by pdemanget** [gkopff/gson-javatime-serialisers#17]
Helllo,
I have Forked your serializers to be used in Java 7 with threeten library, a backport of java8 date time to Java7. It uses another artifactId to not interfere with the Java8 version.
Do you want to publish it to maven? Maybe i could do a pull request by creating a new branch for this variation?

Thank you for your attention
Phil.

**Comment by gkopff** [comment]
I'm happy to publish it.  Perhaps I create a new repo for the threeten version and migrate the code to there?  (That way there would have gson-jodatime-serialiser, gson-javatime-serialiser and gson-threeten-serialisers).

**Comment by pdemanget** [comment]
Yes, it would make sense to create a new repo, it will be very usefull to me. Thanks again.

**Comment by gkopff** [comment]
A new repo has been created here: https://github.com/gkopff/gson-threeten-serialisers

I'll close this issue and further discussion can occur over there ...
