### ISSUE TITLE
Serialisation of Durations

### ISSUE THREAD

**Issue by ifly6** [gkopff/gson-javatime-serialisers#33]
It doesn't seem as if this adds a converter for `java.time.Duration`:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.reflect.ReflectionHelper 
    (file:/Users/ifly6/.m2/repository/com/google/code/gson/gson/2.9.1/gson-2.9.1.jar) to field
    java.time.Duration.seconds
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.ReflectionHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

 Is that intentional?

**Comment by gkopff** [comment]
The warning comes from the reflective operation that Gson performs. Here's stuff about it: https://github.com/google/gson/issues?q=is%3Aissue+%22An+illegal+reflective+access+operation+has+occurred%22

**Comment by gkopff** [comment]
What code are you using to get that?

**Comment by ktdilsiz** [comment]
I'm not getting the same error, but still have problems with Duration. 

Here is my code:
```
        GsonBuilder gsonBuilder = new GsonBuilder();
        Converters.registerAll(gsonBuilder);
        gsonBuilder.registerTypeAdapter(Duration.class, new DurationAdapter());
        Gson gson = gsonBuilder.create();
        GetMetricDataRequest getMetricDataRequest = GetMetricDataRequest.builder().endTime(Instant.now()).build();
        String s = gson.toJson(getMetricDataRequest);

        // Generate dummy PrintWriter object
        PrintWriter writer = new PrintWriter(System.out);
        writer.write(s);
        writer.flush();
```

and here is the DurationAdapter I had to write:
```

public class DurationAdapter extends TypeAdapter<Duration> {

    @Override
    public void write(JsonWriter out, Duration value) throws IOException {
        out.value(value.toString());
    }

    @Override
    public Duration read(JsonReader in) throws IOException {
        return Duration.parse(in.nextString());
    }
}
```

It seems the library is focused on `serialize` and `deserialize` but some of the errors happen around write/read, which would be a good addition to the library.

**Comment by ktdilsiz** [comment]
Another note to add:

This import works (along with most others):
```
import com.fatboyindustrial.gsonjavatime.InstantConverter;
```

But Duration import doesn't work:
```
import com.fatboyindustrial.gsonjavatime.DurationConverter;
```

**Comment by ktdilsiz** [comment]
Ah just needs to be released as a new version :) Duration support was added after 1.1.2 was released.

@gkopff if you ever have the chance to release 1.1.3, I would appreciate it :)

**Comment by gkopff** [comment]
~It looks like the last release done was `1.1.2`, which doesn't have the `Duration` code in it.  That code is in the source tree (`master`) but not released to Maven central.~ EDIT: your latest comment came in as I was writing this.

I'm no longer using this project myself, having switched from Gson to Moshi, so I don't have the spare time to maintain it anymore.  You're welcome to fork it and become its new master :-)

**Comment by ktdilsiz** [comment]
Thank you Greg for the incredibly quick response :) I'll see how things go! Have a wonderful evening!

**Comment by gkopff** [comment]
If you do end up forking it and maintaining a publicly released one, let me know, and I'll update the README to redirect future visitors to you.
